### ISSUE TITLE
Bazelisk no longer compiles with Go 1.11

### ISSUE THREAD

**Issue by mmdriley** [bazelbuild/bazelisk#214]
```
$ go get github.com/bazelbuild/bazelisk
# github.com/bazelbuild/bazelisk/repositories
../../go/src/github.com/bazelbuild/bazelisk/repositories/gcs.go:85:16: undefined: strings.ReplaceAll
```

`strings.ReplaceAll` was [added in Go 1.12](https://golang.org/pkg/strings/#ReplaceAll).

Seems like this use was introduced in #190. Meanwhile, the README [still says](https://github.com/bazelbuild/bazelisk/blob/e93e6d695723c4ef899cc9ebaf7a5f67b522e29b/README.md#requirements):
> The Go version can be compiled to run natively on Linux, macOS and Windows. You need at least Go 1.11 to build Bazelisk

Breaking compatibility with Go 1.11 means Bazelisk can no longer be installed on the [current stable version of Debian](https://www.debian.org/releases/stable/) which [packages Go 1.11](https://packages.debian.org/buster/golang).

Seems worth re-establishing compatibility with Go 1.11, and maybe adding CI to verify that?

**Comment by mmdriley** [comment]
This is a duplicate of #206.
